language: python
python:
  - "2.7"
  - "3.8"
jobs:
  include:
    - name: "Python version 2.7 and 3.8 on Linux"
      os: linux
      before_install:
        - sudo apt-get update
        - sudo apt install python2.7 python-pip
        - sudo add-apt-repository ppa:deadsnakes/ppa -y
        - sudo apt-get update
        - sudo apt install python3.8
        - sudo apt install python3-pip
        - sudo pip install tox

    - name: "macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
      before_install:
        - sudo pip install tox
    - name: "Python version 2.7 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 2.7.17
        - python -m pip install --upgrade pip
        - pip install tox
      env: PATH=/c/Python27:/c/Python27/Scripts:$PATH
    - name: "With Python version 3.8 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
        - pip install tox
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install: pip3 install --upgrade pip
script:
  - tox -e short-test
