language: bash

os:
  - windows

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install -y miniconda3; fi
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; then conda install virtualenv; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then pip install tox                             ; fi

script:
  - tox -e short-test
