language: bash

os:
  - windows

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then python -m pip install --upgrade pip         ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then pip install tox                             ; fi

script:
  - tox -e short-test
