language: bash

os:
  - windows

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then sudo python -m pip install --upgrade pip         ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then sudo pip install tox             ; fi

script:
  - tox -e short-test
