language: python
jobs:
  include:
    - name: "Linux"
      os: linux
      before_install:
        - sudo apt update
        - sudo apt install python3-pip
        - sudo pip install tox
    - name: "macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
      before_install:
        - sudo pip install tox
    - name: "Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
        - pip install tox
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install: pip3 install --upgrade pip
script:
  - tox -e short-test
