language: bash

os:
  - windows
  env: PATH=/c/Python38:/c/Python38/Scripts:$PATH


before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install python     ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then pip install tox             ; fi

script:
  - tox -e short-test
