language: bash

os:
  - windows

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install python --pre     ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install pip            ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then pip install tox             ; fi

script:
  - tox -e short-test
